INCORRECT_LOGIN = "Incorrect email or password."
EMAIL_TAKEN = "User already exists with this email."
INCORRECT_PERMS = "Operation not permitted."
USER_NOT_FOUND = "User cannot be found."
USER_DELETED = "User successfully deleted."
NEMWEB_UNIT_NOT_FOUND = "Requested Unit(s) could not be found."